# 총 사용금액 TOT_AMT 열로 계산, 내림차순 정렬
SELECT CMF, PARTY_NM, (COALESCE(PIF_AMT, 0)+COALESCE(INST_AMT, 0)+COALESCE(OVRS_AMT, 0)+COALESCE(CASH_AMT, 0)) AS TOT_AMT FROM card_tran_201311 ORDER BY TOT_AMT DESC;

# 할부 결제 이용한 고객 찾기
SELECT CMF, PARTY_NM, INST_AMT FROM card_tran_201311 WHERE INST_AMT IS NOT NULL;

# PB고객 대상 일시불 사용금액의 10% 캐시백 -> 얼마?
SELECT CMF, PARTY_NM, SEG, PIF_AMT, COALESCE(PIF_AMT, 0)*0.1 AS REWARDS FROM card_tran_201311 WHERE SEG = 'PB';