# ES 문자를 포함하는 도시 중 세 달 연속 구매 금액이 3백만원 넘는 고객
SELECT * 
FROM cust_perf 
WHERE COALESCE(TOT_AMT_1, 0) >= 3000000
    AND COALESCE(TOT_AMT_2, 0) >= 3000000
    AND COALESCE(TOT_AMT_3, 0) >= 3000000
    AND CITY LIKE '%ES%';

# "DEAR LEE, YOUR SEGMENT IS PRIORITY IN OUR COMPANY." 문구 만들기
SELECT CONCAT(CONCAT(CONCAT(CONCAT('DEAR ',TRIM(NAME)),', YOUR SEGMENT IS '),TRIM(SEG)),' IN OUR COMPANY.') AS DM
FROM cust_perf 
WHERE COALESCE(TOT_AMT_1, 0) >= 3000000
    AND COALESCE(TOT_AMT_2, 0) >= 3000000
    AND COALESCE(TOT_AMT_3, 0) >= 3000000
    AND CITY LIKE '%ES%';
