# 현재 연체일이 30일 미만인 사람들의 주민번호, 이름, 휴대폰 번호
SELECT SSN, PARTY_NM, MOBILE_NO
FROM CUST_PARTY
WHERE SSN IN (SELECT DISTINCT SSN
                FROM DLQ_PARTY
                WHERE DLQ_DURATION < 30 AND CURR_DLQ = 'Y');

# 현재 연체중 또는 과거에 연체 이력 10일 이상 
# 외부조인 사용
SELECT TMP1.SSN, TMP1.PARTY_NM, TMP1.MOBILE_NO, TMP2.DLQ_FLAG
FROM CUST_PARTY AS TMP1
LEFT OUTER JOIN (SELECT DISTINCT SSN, 1 AS DLQ_FLAG
                    FROM DLQ_PARTY
                    WHERE CURR_DLQ='Y' OR (CURR_DLQ='N' AND DLQ_DURATION>=10)) AS TMP2
ON TMP1.SSN = TMP2.SSN
WHERE TMP2.DLQ_FLAG IS NOT NULL
;

# 위 문제를 WHERE 조건절에 하위쿼리로 변경
SELECT SSN, PARTY_NM, MOBILE_NO
FROM CUST_PARTY
WHERE SSN IN (SELECT DISTINCT SSN
                FROM DLQ_PARTY
                WHERE CURR_DLQ='Y' OR (CURR_DLQ='N' AND DLQ_DURATION>=10));

# 현재 연체중인 고객의 최대 연체일 수 산출
# XXX 고객님의 현재 연체일 수는 XX일입니다. 문구
# 주민번호, 이름, 휴대폰 번호, 연체일 수
SELECT TMP1.SSN, TMP1.PARTY_NM, TMP1.MOBILE_NO, TMP2.DLQ_DURATION,
         CONCAT(CONCAT(CONCAT(PARTY_NM, '고객님의 현재 연체일 수는'), DLQ_DURATION), '일입니다')
FROM CUST_PARTY AS TMP1
INNER JOIN(SELECT SSN, MAX(DLQ_DURATION) AS DLQ_DURATION
           FROM DLQ_PARTY
           WHERE CURR_DLQ='Y'
           GROUP BY 1) AS TMP2
ON TMP1.SSN = TMP2.SSN;