# 직급 확인
SELECT DISTINCT position FROM emp;

# 직급에 따른 인사고과
SELECT DISTINCT position, grade FROM emp;

# ID를 CLERK_ID, GRADE를 PERF로 이름 부여
SELECT ID AS CLERK_ID, POSITION, PARTY_NM, MANAGER_ID,
TEAM_NM,GRADE AS PERF FROM emp;

SELECT ID "CLERK_ID", POSITION, PARTY_NM, MANAGER_ID,
TEAM_NM,GRADE "PERF" FROM emp;

# 인사고과를 주는 사람들 구하기
SELECT DISTINCT MANAGER_ID FROM emp;

# 인사고과를 몇명이 주는지 구하기
SELECT COUNT(DISTINCT MANAGER_ID) FROM emp;

# 별칭을 사용해 인사고과를 몇 명이 주는지 구하기
SELECT COUNT(DISTINCT MANAGER_ID) AS CNT FROM emp;

# 인용부호 사용
SELECT COUNT(DISTINCT MANAGER_ID) "CNT" FROM emp;