# ACCT_CD가 100대면 부채, 300대면 자산, 그룹 별 총 금액
SELECT
      CASE WHEN ACCT_CD >= 300 THEN 'LIABILITY'
           ELSE 'ASSET'
      END AS BALANCE_SHEET,
      SUM(BALANCE_AMT) AS total_BALANCE_AMT
FROM PPC_MAST_201312
GROUP BY 1;

# 고객당 가입상품개수
SELECT SSN, COUNT(*) AS PPC
FROM PPC_MAST_201312
GROUP BY 1
ORDER BY 1;

# 고객당 가입상품개수가 3개이상인 고객
SELECT SSN, COUNT(*) AS PPC
FROM PPC_MAST_201312
GROUP BY 1
HAVING COUNT(*) > 2
ORDER BY 1;

# PPC와 총 수익
SELECT SSN, COUNT(*) AS PPC, SUM(PRFT) AS PRFT
FROM PPC_MAST_201312
GROUP BY 1
ORDER BY 1;